let sampleDivs = document.getElementsByClassName("sample-text");

console.log(sampleDivs)

for (let div of sampleDivs) {
    console.log(div);
    div.innerHTML = 
    `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat est velit egestas dui. Justo donec enim diam vulputate ut pharetra sit. Eget egestas purus viverra accumsan in nisl nisi scelerisque. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Nulla posuere sollicitudin aliquam ultrices. Posuere ac ut consequat semper viverra nam. Quam lacus suspendisse faucibus interdum. Eu sem integer vitae justo. Velit euismod in pellentesque massa placerat. Magna ac placerat vestibulum lectus mauris. Iaculis nunc sed augue lacus viverra vitae congue eu consequat. Tincidunt vitae semper quis lectus nulla at volutpat diam. At auctor urna nunc id cursus metus aliquam. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Ac placerat vestibulum lectus mauris ultrices eros in cursus turpis.</p>
    <p>Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Venenatis tellus in metus vulputate eu scelerisque felis. Amet justo donec enim diam. Feugiat pretium nibh ipsum consequat nisl. Augue ut lectus arcu bibendum. Lacinia at quis risus sed. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Varius morbi enim nunc faucibus a pellentesque sit. Vestibulum morbi blandit cursus risus at ultrices mi tempus. Augue neque gravida in fermentum et sollicitudin. Augue neque gravida in fermentum et sollicitudin. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Purus sit amet volutpat consequat. Mauris sit amet massa vitae tortor condimentum. Enim nulla aliquet porttitor lacus luctus accumsan tortor. Non pulvinar neque laoreet suspendisse interdum consectetur libero id. Rhoncus urna neque viverra justo nec ultrices dui. Elementum curabitur vitae nunc sed. Mauris in aliquam sem fringilla ut morbi. Ultrices neque ornare aenean euismod elementum nisi.</p>
    <p>Posuere urna nec tincidunt praesent semper feugiat. Duis tristique sollicitudin nibh sit amet. Quis lectus nulla at volutpat. In fermentum posuere urna nec tincidunt praesent. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Nulla aliquet enim tortor at auctor urna nunc id. Ut diam quam nulla porttitor massa id neque aliquam. Ullamcorper velit sed ullamcorper morbi tincidunt. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Consequat mauris nunc congue nisi vitae suscipit tellus. Augue ut lectus arcu bibendum. Quam quisque id diam vel quam.</p>`
}